src/NuGetGallery/Areas/Admin/ViewModels/LockPackageViewModel.cs
// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.Collections.Generic;

namespace NuGetGallery.Areas.Admin.ViewModels
{
    public class LockPackageViewModel
    {
        public string Query { get; set; }

        public bool HasQuery => !string.IsNullOrEmpty(Query);

        public bool HasResults => PackageLockStates?.Count > 0;

        public IList<PackageLockState> PackageLockStates { get; set; }
    }

    public class PackageLockState
    {
        public string Id { get; set; }
        public bool IsLocked { get; set; }
    }
}

src/NuGetGallery/Areas/Admin/Controllers/LockPackageController.cs
// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using NuGet.Services.Entities;
using NuGetGallery.Areas.Admin.ViewModels;

namespace NuGetGallery.Areas.Admin.Controllers
{
    public class LockPackageController : AdminControllerBase
    {
        private IEntityRepository<PackageRegistration> _packageRegistrationRepository;

        public LockPackageController(IEntityRepository<PackageRegistration> packageRegistrationRepository)
        {
            _packageRegistrationRepository = packageRegistrationRepository ?? throw new ArgumentNullException(nameof(packageRegistrationRepository));
        }

        [HttpGet]
        public virtual ActionResult Index()
        {
            var model = new LockPackageViewModel();

            return View(model);
        }

        [HttpGet]
        public virtual ActionResult Search(string query)
        {
            var lines = Helpers.ParseQueryToLines(query);
            var packageRegistrations = GetPackageRegistrationsForIds(lines);

            return View(nameof(Index), new LockPackageViewModel()
            {
                Query = query,
                PackageLockStates = packageRegistrations.Select(x => new PackageLockState() { Id = x.Id, IsLocked = x.IsLocked }).ToList()
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(LockPackageViewModel lockPackageViewModel)
        {
            int counter = 0;

            if (lockPackageViewModel != null && lockPackageViewModel.PackageLockStates != null)
            {
                var packageIdsFromRequest = lockPackageViewModel.PackageLockStates.Select(x => x.Id).ToList();
                var packageRegistrationsFromDb = GetPackageRegistrationsForIds(packageIdsFromRequest);

                var packageStatesFromRequestDictionary = lockPackageViewModel.PackageLockStates.ToDictionary(x => x.Id);

                foreach (var packageRegistration in packageRegistrationsFromDb)
                {
                    if (packageStatesFromRequestDictionary.TryGetValue(packageRegistration.Id, out var packageStateRequest))
                    {
                        if (packageRegistration.IsLocked != packageStateRequest.IsLocked)
                        {
                            packageRegistration.IsLocked = packageStateRequest.IsLocked;
                            counter++;
                        }
                    }
                }

                if (counter > 0)
                {
                    await _packageRegistrationRepository.CommitChangesAsync();
                }
            }

            TempData["Message"] = string.Format(CultureInfo.InvariantCulture, $"Lock state was updated for {counter} packages.");

            return View(nameof(Index), lockPackageViewModel);
        }

        private IList<PackageRegistration> GetPackageRegistrationsForIds(IReadOnlyList<string> ids)
        {
            return _packageRegistrationRepository.GetAll().Where(x => ids.Contains(x.Id)).ToList();
        }
    }
}

src/NuGetGallery/Areas/Admin/Views/LockPackage/Index.cshtml
@model LockPackageViewModel
@{
    ViewBag.Title = "Package Locking";
}

<section role="main" class="container main-container">
    <h2>Package Locking</h2>

    <form method="get" action="@Url.Action(actionName: "Search")">
        <p>
            <textarea name="query" placeholder="Search for package ids..." autocomplete="off" autofocus style="width: 100%" rows="5">@Model.Query</textarea>
        </p>
        <p>
            <input type="submit" value="Search" />
        </p>
    </form>

    @if (Model.HasQuery && !Model.HasResults)
    {
        <p>No results found.</p>
    }
    else if (!Model.HasQuery)
    {
        <p>To search for multiple packages use a separate line for each Package Id.</p>
    }

    @if (Model.PackageLockStates != null && Model.PackageLockStates.Any())
    {
        using (Html.BeginForm("Update", "LockPackage", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Query)
            <div>
                <h3>Results</h3>
                <br />
                <button type="button" onclick="selectall()">Select All</button>
                <button type="button" onclick="deselectall()">Deselect All</button>
                <p>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Is Locked?</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.PackageLockStates.Count; i++)
                            {
                                <tr>
                                    <td>@Html.DisplayTextFor(model => model.PackageLockStates[i].Id)</td>
                                    @Html.HiddenFor(model => model.PackageLockStates[i].Id)
                                    <td>@Html.CheckBoxFor(model => model.PackageLockStates[i].IsLocked, new { @class = "islockedcheckbox" })</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </p>
                <p>
                    <input type="submit" value="Apply" />
                </p>
            </div>
        }
    }

</section>

@section BottomScripts {
    <script>
        function selectall() {
            $('.islockedcheckbox:checkbox').each(function () {
                $(this).prop('checked', true);
            })
        }

        function deselectall() {
            $('.islockedcheckbox:checkbox').each(function () {
                $(this).prop('checked', false);
            })
        }
    </script>
}