src/NuGetGallery/ViewModels/ApiKeyViewModel.cs
// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.Linq;

namespace NuGetGallery
{
    public class ApiKeyViewModel
    {
        public ApiKeyViewModel()
        {
        }

        public ApiKeyViewModel(CredentialViewModel cred)
        {
            if (cred == null)
            {
                throw new ArgumentNullException(nameof(cred));
            }

            if (cred.Scopes == null)
            {
                throw new ArgumentNullException(nameof(cred.Scopes));
            }

            // Currently ApiKeys.cshtml has single Owner per ApiKey restriction.
            var owner = cred
                .Scopes
                .Select(s => s.Owner)
                .Distinct()
                .SingleOrDefault();

            var scopes = cred
                .Scopes
                .Select(s => s.AllowedAction)
                .Distinct()
                .OrderBy(s => s)
                .ToList();

            var subjects = cred
                .Scopes
                .Select(s => s.Subject)
                .Distinct()
                .OrderBy(s => s)
                .ToList();

            var globPattern = subjects
                .FirstOrDefault(s => s != null && s.Contains("*"));

            var packages = subjects
                .Except(new[] { globPattern })
                .ToList();

            Key = cred.Key;
            Type = cred.Type;
            Value = cred.Value;
            Description = cred.Description;
            Expires = cred.Expires?.ToString("O");
            HasExpired = cred.HasExpired;
            IsNonScopedApiKey = cred.IsNonScopedApiKey;
            RevocationSource = cred.RevocationSource;
            Owner = owner;
            Scopes = scopes;
            Packages = packages;
            GlobPattern = globPattern;
        }

        public bool IsNonScopedApiKey { get; set; }
        public bool HasExpired { get; set; }
        public string Expires { get; set; }
        public string Owner { get; set; }
        public IList<string> Scopes { get; set; }
        public IList<string> Packages { get; set; }
        public string GlobPattern { get; set; }
        public string Value { get; set; }
        public string Type { get; set; }
        public int Key { get; set; }
        public string Description { get; set; }
        public string RevocationSource { get; set; }
    }
}

src/NuGetGallery/Areas/Admin/Controllers/ApiKeysController.cs
// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Collections.Generic;
using Newtonsoft.Json;
using NuGet.Services.Entities;
using NuGetGallery.Authentication;
using NuGet.Services.Messaging.Email;
using NuGetGallery.Areas.Admin.Models;
using NuGetGallery.Areas.Admin.ViewModels;
using NuGetGallery.Infrastructure.Mail.Messages;

namespace NuGetGallery.Areas.Admin.Controllers
{
    public class ApiKeysController : AdminControllerBase
    {
        private readonly IAuthenticationService _authenticationService;
        private readonly ITelemetryService _telemetryService;
        private readonly IEntitiesContext _entitiesContext;
        private readonly IMessageService _messageService;
        private readonly IMessageServiceConfiguration _messageServiceConfiguration;

        public ApiKeysController(IAuthenticationService authenticationService,
            ITelemetryService telemetryService,
            IEntitiesContext entitiesContext,
            IMessageService messageService,
            IMessageServiceConfiguration messageServiceConfiguration)
        {
            _authenticationService = authenticationService ?? throw new ArgumentNullException(nameof(authenticationService));
            _telemetryService = telemetryService ?? throw new ArgumentNullException(nameof(telemetryService));
            _entitiesContext = entitiesContext ?? throw new ArgumentNullException(nameof(entitiesContext));
            _messageService = messageService ?? throw new ArgumentNullException(nameof(messageService));
            _messageServiceConfiguration = messageServiceConfiguration ?? throw new ArgumentNullException(nameof(messageServiceConfiguration));
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Verify(string verifyQuery)
        {
            if (string.IsNullOrWhiteSpace(verifyQuery))
            {
                return Json(HttpStatusCode.BadRequest, "Invalid empty input!");
            }

            var queries = verifyQuery.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries).Select(q => q.Trim()).ToList();

            var results = new List<ApiKeyRevokeViewModel>();
            var verifiedApiKey = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var query in queries)
            {
                try
                {
                    var leakedApiKeyInfo = JsonConvert.DeserializeObject<LeakedApiKeyInfo>(query);

                    var apiKey = leakedApiKeyInfo.ApiKey;
                    if (!verifiedApiKey.Add(apiKey))
                    {
                        continue;
                    }
                    var leakedUrl = leakedApiKeyInfo.LeakedUrl;
                    var revocationSource = leakedApiKeyInfo.RevocationSource;

                    var credential = _authenticationService.GetApiKeyCredential(apiKey);
                    if (credential == null)
                    {
                        results.Add(new ApiKeyRevokeViewModel(apiKeyViewModel: null, apiKey: apiKey, leakedUrl: null, revocationSource: null, isRevocable: false));
                        continue;
                    }

                    var apiKeyViewModel = new ApiKeyViewModel(_authenticationService.DescribeCredential(credential));
                    if (!_authenticationService.IsActiveApiKeyCredential(credential))
                    {
                        results.Add(new ApiKeyRevokeViewModel(apiKeyViewModel, apiKey, leakedUrl: null, revocationSource: apiKeyViewModel.RevocationSource, isRevocable: false));
                        continue;
                    }
                    if (!Enum.TryParse(revocationSource, out CredentialRevocationSource revocationSourceKey))
                    {
                        return Json(HttpStatusCode.BadRequest, $"Invalid input! {query} is not using the supported Revocation Source: " +
                            $"{string.Join(",", Enum.GetNames(typeof(CredentialRevocationSource)))}.");
                    }

                    results.Add(new ApiKeyRevokeViewModel(apiKeyViewModel, apiKey, leakedUrl, revocationSource, isRevocable: true));
                }
                catch (JsonException)
                {
                    return Json(HttpStatusCode.BadRequest, $"Invalid input! {query} is not using the valid JSON format.");
                }
            }

            return Json(HttpStatusCode.OK, results);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Revoke(RevokeApiKeysRequest revokeApiKeysRequest)
        {
            if (revokeApiKeysRequest == null)
            {
                TempData["ErrorMessage"] = "The API keys revoking request can not be null.";
                return View(nameof(Index));
            }
            if (revokeApiKeysRequest.SelectedApiKeys == null || revokeApiKeysRequest.SelectedApiKeys.Count == 0)
            {
                TempData["ErrorMessage"] = "The API keys revoking request contains null or empty selected API keys.";
                return View(nameof(Index));
            }

            try
            {
                foreach (var selectedApiKey in revokeApiKeysRequest.SelectedApiKeys)
                {
                    var apiKeyInfo = JsonConvert.DeserializeObject<ApiKeyRevokeViewModel>(selectedApiKey);

                    var apiKeyCredential = _authenticationService.GetApiKeyCredential(apiKeyInfo.ApiKey);
                    var revocationSourceKey = (CredentialRevocationSource)Enum.Parse(typeof(CredentialRevocationSource), apiKeyInfo.RevocationSource);

                    var credentialRevokedMessage = new CredentialRevokedMessage(
                        _messageServiceConfiguration,
                        credential: apiKeyCredential,
                        leakedUrl: apiKeyInfo.LeakedUrl,
                        revocationSource: apiKeyInfo.RevocationSource,
                        manageApiKeyUrl: Url.ManageMyApiKeys(relativeUrl: false),
                        contactUrl: Url.Contact(relativeUrl: false));
                    await _messageService.SendMessageAsync(credentialRevokedMessage);

                    await _authenticationService.RevokeApiKeyCredential(apiKeyCredential, revocationSourceKey, commitChanges: false);
                }

                await _entitiesContext.SaveChangesAsync();
            }
            catch (Exception e)
            {
                _telemetryService.TraceException(e);
                TempData["ErrorMessage"] = "Failed to revoke the API keys, and please check the telemetry for details.";
                return RedirectToAction("Index");
            }

            TempData["Message"] = "Successfully revoke the selected API keys.";
            return RedirectToAction("Index");
        }

        private class LeakedApiKeyInfo
        {
            [JsonProperty("ApiKey", Required = Required.Always)]
            public string ApiKey { get; set; }

            [JsonProperty("LeakedUrl", Required = Required.Always)]
            public string LeakedUrl { get; set; }

            [JsonProperty("RevocationSource", Required = Required.Always)]
            public string RevocationSource { get; set; }
        }
    }
}

src/NuGetGallery/Areas/Admin/Views/ApiKeys/Index.cshtml
@model NuGetGallery.Areas.Admin.Models.RevokeApiKeysRequest
@{
    ViewBag.Title = "Revoke API Keys";
}
@ViewHelpers.AjaxAntiForgeryToken(Html)

<section role="main" class="container main-container">
    <h2>Verify API Keys</h2>
    <p class="text-muted">
        Please follow the format as below: <br />
        {"ApiKey":"oy2apikey1","LeakedUrl":"https://leakedUrl1","RevocationSource":"GitHub"} <br />
        {"ApiKey":"oy2apikey2","LeakedUrl":"https://leakedUrl2","RevocationSource":"GitHub"}
    </p>
    <form>
        <textarea class="form-control" placeholder="Verify API keys to revoke" autocomplete="off" autofocus rows="5" data-bind="value: verifyQuery"></textarea><br />
        <input type="button" value="Verify" data-bind="click: verify" /><br />
    </form>
    <div style="display: none" data-bind="visible: Error">
        @ViewHelpers.AlertDanger(@<text><span data-bind="html: Error"></span></text>)
    </div>
    @using (Html.BeginForm("Revoke", "ApiKeys", new { area = "Admin" }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <table class="table break-word" style="display: none" data-bind="visible: verifiedResults().length > 0">
            <thead>
                <tr>
                    <th class="col-sm-1">
                        <input type="checkbox" data-bind="visible: findAnyRevocableApiKeys, click: toggleSelectAllRevocableApiKeys, checked: selectAllRevocableApiKeys" />
                    </th>
                    <th class="col-sm-5">Api Key</th>
                    <th class="col-sm-6">Information</th>
                </tr>
            </thead>
            <tbody data-bind="foreach: verifiedResults">
                <tr>
                    <td class="col-sm-1" style="vertical-align: middle">
                        <input type="checkbox" name="SelectedApiKeys" data-bind="visible: IsRevocable, checked: Selected, value: ko.toJSON($data)" />
                    </td>
                    <td class="col-sm-5" style="vertical-align: middle">
                        <span data-bind="text: ApiKey"></span>
                    </td>
                    <td class="col-sm-6" style="vertical-align: middle">
                        <!-- ko if: ApiKeyViewModel -->
                        <span data-bind="visible: ApiKeyViewModel.Type">
                            <code>Type:</code> <span data-bind="text: ApiKeyViewModel.Type"></span><br />
                        </span>
                        <span data-bind="visible: ApiKeyViewModel.Owner">
                            <code>Owner:</code> <a data-bind="text: ApiKeyViewModel.Owner, attr: { href: $parent.generateProfileUrl(ApiKeyViewModel.Owner) }"></a><br />
                        </span>
                        <span>
                            <code>Status:</code>
                            <!-- ko if: ApiKeyViewModel.HasExpired -->
                            Expired <br />
                            <!-- /ko -->
                            <!-- ko ifnot: ApiKeyViewModel.HasExpired -->
                            <!-- ko if: ApiKeyViewModel.Expires -->
                            Expires <span data-bind="text: moment(ApiKeyViewModel.Expires).fromNow()"></span><br />
                            <!-- /ko -->
                            <!-- ko ifnot: ApiKeyViewModel.Expires -->
                            Never expires<br />
                            <!-- /ko -->
                            <!-- /ko -->
                        </span>
                        <span data-bind="visible: ApiKeyViewModel.Description">
                            <code>Description:</code> <span data-bind="text: ApiKeyViewModel.Description"></span><br />
                        </span>
                        <!-- ko if: LeakedUrl -->
                        <code>Leaked Url:</code> <a data-bind="attr: { href: LeakedUrl }">Link</a><br />
                        <!-- /ko -->
                        <!-- ko if: !IsRevocable && RevocationSource  -->
                        <code>Revocation Source:</code> <span data-bind="text: RevocationSource"></span><br />
                        <!-- /ko -->
                        <!-- /ko -->
                        <!-- ko ifnot: ApiKeyViewModel -->
                        Not Found
                        <!-- /ko -->
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="form-group" style="display: none" data-bind="visible: AreAnyRevocableApiKeysSelected">
            <hr />
            <p>
                This will expire and revoke the selected API keys, and send the emails to notify customers!
            </p>
            <hr />
            <input type="submit" class="btn btn-danger form-control" value="I understand the consequences, revoke the API keys" />
        </div>
    }
</section>

@section BottomScripts {
    <script>
        $(document).ready(function () {
            var viewModel = function () {
                var $self = this;

                this.verifyQuery = ko.observable('');
                this.verifiedResults = ko.observableArray([]);
                this.selectAllRevocableApiKeys = ko.observable(false);
                this.Error = ko.observable(null);

                this.verify = function () {
                    $self.verifiedResults.removeAll();
                    $self.selectAllRevocableApiKeys(false);
                    $self.Error(null);

                    $.ajax({
                        url: '@Url.Action("Verify", "ApiKeys", new {area = "Admin"})',
                        cache: false,
                        dataType: 'json',
                        type: 'POST',
                        data: window.nuget.addAjaxAntiForgeryToken({ verifyQuery: $self.verifyQuery() }),
                        success: function(data) {
                            for (var i = 0; i < data.length; i++) {
                                data[i].Selected = ko.observable(false);
                            }
                            $self.verifiedResults(data);
                        }
                    })
                    .fail(function(jqXhr, textStatus, errorThrown) {
                        var error = "Unknown error when verifying the API keys!";
                        if (jqXhr.responseJSON) {
                            error = jqXhr.responseJSON;
                        }
                        $self.Error(error);
                    });
                };

                this.generateProfileUrl = function (u) {
                    return '/profiles/' + u;
                };

                this.findAnyRevocableApiKeys = ko.pureComputed(function () {
                    var results = $self.verifiedResults();
                    if (!results || results.length === 0) {
                        return false;
                    }

                    for (var i = 0; i < results.length; i++) {
                        if (results[i].IsRevocable) {
                            return true;
                        }
                    }

                    return false;
                });

                this.AreAnyRevocableApiKeysSelected = ko.computed(function() {
                    var results = $self.verifiedResults();
                    for (var i = 0; i < results.length; i++) {
                        if (results[i].Selected()) {
                            return true;
                        }
                    }

                    return false;
                });

                this.toggleSelectAllRevocableApiKeys = function() {
                    $self.selectAllRevocableApiKeys(!$self.selectAllRevocableApiKeys());
                    return true;
                };

                this.selectAllRevocableApiKeys.subscribe(function() {
                    var state = $self.selectAllRevocableApiKeys();
                    ko.utils.arrayForEach($self.verifiedResults(), function (result) {
                        if (result.IsRevocable) {
                            result.Selected(state);
                        }
                    });
                });
            };

            ko.applyBindings(new viewModel(), $('#stage').get(0));
        });
    </script>
}