src/NuGetGallery/Areas/Admin/ViewModels/SiteAdminsViewModel.cs
// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.Collections.Generic;

namespace NuGetGallery.Areas.Admin.ViewModels
{
    public class SiteAdminsViewModel
    {
        public IEnumerable<string> AdminUsernames { get; set; }
    }
}

src/NuGetGallery/Areas/Admin/Controllers/SiteAdminsController.cs
// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using NuGetGallery.Areas.Admin.ViewModels;

namespace NuGetGallery.Areas.Admin.Controllers
{
    public class SiteAdminsController : AdminControllerBase
    {
        private readonly IUserService _userService;

        public SiteAdminsController(IUserService userService)
        {
            _userService = userService ?? throw new ArgumentNullException(nameof(userService));
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(
                new SiteAdminsViewModel
                {
                    AdminUsernames = _userService.GetSiteAdmins().Select(u => u.Username)
                });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Task<ActionResult> AddAdmin(string username)
        {
            return SetIsAdministrator(username, true);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Task<ActionResult> RemoveAdmin(string username)
        {
            return SetIsAdministrator(username, false);
        }

        private async Task<ActionResult> SetIsAdministrator(string username, bool isAdmin)
        {
            var user = _userService.FindByUsername(username);
            if (user == null)
            {
                TempData["ErrorMessage"] = $"User '{username}' does not exist!";
            }
            else
            {
                await _userService.SetIsAdministrator(user, isAdmin);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

src/NuGetGallery/Areas/Admin/Views/SiteAdmins/Index.cshtml
@model SiteAdminsViewModel
@{
    ViewBag.Title = "Site Admins";
}

<section role="main" class="container main-container">
    <h2>Current Admins</h2>
    <table class="table">
        @foreach (var adminUsername in Model.AdminUsernames)
        {
            <tr>
                @using (Html.BeginForm("RemoveAdmin", "SiteAdmins"))
                {
                    <th>
                        <a href="@Url.User(adminUsername)"
                           title="View profile of @adminUsername">
                            @adminUsername
                        </a>
                    </th>
                    <th>
                        @Html.AntiForgeryToken()
                        @Html.Hidden("username", adminUsername)
                        <button class="btn-link">
                            <span>Remove</span>
                        </button>
                    </th>
                }
            </tr>
        }
    </table>

    <h2>Add Admin</h2>
    @using (Html.BeginForm("AddAdmin", "SiteAdmins"))
    {
        @Html.AntiForgeryToken()
        <input type="text" name="username" />
        <button type="submit">Add</button>
    }
</section>