src/NuGetGallery/Areas/Admin/Controllers/FeaturesController.cs
// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using NuGet.Services.FeatureFlags;
using NuGetGallery.Areas.Admin.ViewModels;
using NuGetGallery.Configuration;
using NuGetGallery.Features;

namespace NuGetGallery.Areas.Admin.Controllers
{
    public class FeaturesController : AdminControllerBase
    {
        private readonly IUserService _userService;
        private readonly IEditableFeatureFlagStorageService _storage;
        private readonly IFeatureFlagCacheService _cache;
        private readonly IAppConfiguration _config;

        public FeaturesController(
            IUserService userService,
            IEditableFeatureFlagStorageService storage,
            IFeatureFlagCacheService cache,
            IAppConfiguration config)
        {
            _userService = userService ?? throw new ArgumentNullException(nameof(userService));
            _storage = storage ?? throw new ArgumentNullException(nameof(storage));
            _cache = cache ?? throw new ArgumentNullException(nameof(cache));
            _config = config ?? throw new ArgumentNullException(nameof(config));
        }

        [HttpGet]
        public async virtual Task<ActionResult> Index()
        {
            return View(await GetModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Task<ActionResult> AddFeature(ModifyFeatureFlagsFeatureViewModel feature)
        {
            return MergeChangesAndTrySave<ModifyFeatureFlagsFeatureViewModel, FeatureFlagsFeatureViewModel>(
                feature,
                ChangeType.Add);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Task<ActionResult> EditFeature(ModifyFeatureFlagsFeatureViewModel feature)
        {
            return MergeChangesAndTrySave<ModifyFeatureFlagsFeatureViewModel, FeatureFlagsFeatureViewModel>(
                feature,
                ChangeType.Edit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Task<ActionResult> DeleteFeature(ModifyFeatureFlagsFeatureViewModel feature)
        {
            return MergeChangesAndTrySave<ModifyFeatureFlagsFeatureViewModel, FeatureFlagsFeatureViewModel>(
                feature,
                ChangeType.Delete);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Task<ActionResult> AddFlight(ModifyFeatureFlagsFlightViewModel flight)
        {
            return MergeChangesAndTrySave<ModifyFeatureFlagsFlightViewModel, FeatureFlagsFlightViewModel>(
                flight,
                ChangeType.Add);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Task<ActionResult> EditFlight(ModifyFeatureFlagsFlightViewModel flight)
        {
            return MergeChangesAndTrySave<ModifyFeatureFlagsFlightViewModel, FeatureFlagsFlightViewModel>(
                flight,
                ChangeType.Edit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Task<ActionResult> DeleteFlight(ModifyFeatureFlagsFlightViewModel flight)
        {
            return MergeChangesAndTrySave<ModifyFeatureFlagsFlightViewModel, FeatureFlagsFlightViewModel>(
                flight,
                ChangeType.Delete);
        }

        private async Task<ActionResult> MergeChangesAndTrySave<TModify, TBase>(
            TModify change,
            ChangeType type)
            where TModify : IModifyFeatureFlagsViewModel<TBase>, TBase
            where TBase : IFeatureFlagsObjectViewModel
        {
            var model = await GetModel();

            var errorMessage = ValidateModelState() 
                ?? ApplyChange<TModify, TBase>(model, change, type) 
                ?? await TrySaveFlags(model, change.ContentId);
            if (errorMessage != null)
            {
                TempData["ErrorMessage"] = errorMessage;
            }

            return RedirectToAction(nameof(Index));
        }

        private string ApplyChange<TModify, TBase>(
            FeatureFlagsViewModel model,
            TModify change,
            ChangeType type)
            where TModify : IModifyFeatureFlagsViewModel<TBase>, TBase
            where TBase : IFeatureFlagsObjectViewModel
        {
            var validationError = change.GetValidationError(_userService);
            if (validationError != null)
            {
                return validationError;
            }

            var existingList = change.GetExistingList(model);
            var existing = existingList.SingleOrDefault(f => f.Name == change.Name);
            switch (type)
            {
                case ChangeType.Add:
                    if (existing == null)
                    {
                        existingList.Add(change);
                        return null;
                    }
                    else
                    {
                        return $"The {change.PrettyName} '{change.Name}' already exists. " +
                            $"You cannot add a {change.PrettyName} that already exists.";
                    }

                case ChangeType.Edit:
                    if (existing == null)
                    {
                        return $"The {change.PrettyName} '{change.Name}' does not exist. " +
                            $"You cannot edit a {change.PrettyName} that does not exist.";
                    }
                    else
                    {
                        change.ApplyTo(existing);
                        return null;
                    }

                case ChangeType.Delete:
                    if (existing == null)
                    {
                        return $"The {change.PrettyName} '{change.Name}' does not exist. " +
                            $"You cannot delete a {change.PrettyName} that does not exist.";
                    }
                    else
                    {
                        existingList.Remove(existing);
                        return null;
                    }

                default:
                    throw new ArgumentOutOfRangeException(nameof(type));
            }
        }

        private string ValidateModelState()
        {
            if (ModelState.IsValid)
            {
                return null;
            }

            var errorMessages = ModelState
                .SelectMany(s => s.Value.Errors)
                .Select(e => e.ErrorMessage)
                .Where(e => !string.IsNullOrWhiteSpace(e));

            return errorMessages.Any()
                ? "The model submitted was invalid: " + string.Join(" ", errorMessages)
                : "The model submitted was invalid.";
        }

        private async Task<string> TrySaveFlags(FeatureFlagsViewModel model, string contentId)
        {
            var flags = new FeatureFlags(
                model.Features.ToDictionary(f => f.Name, f => f.Status),
                model.Flights.ToDictionary(f => f.Name, f => f.AsFlight()));

            var result = await _storage.TrySaveAsync(flags, contentId);

            switch (result)
            {
                case FeatureFlagSaveResult.Ok:
                    // The flags have been persisted. Refresh this instance's cache immediately.
                    await _cache.RefreshAsync();

                    var refreshSeconds = _config.FeatureFlagsRefreshInterval.TotalSeconds;
                    TempData["Message"] = $"Your feature flags have been saved! It may take up to {refreshSeconds} seconds for this change to propagate everywhere.";
                    return null;

                case FeatureFlagSaveResult.Conflict:
                    return "Your changes were not applied as the feature flags were modified by someone else. Please reload the page and try again.";

                default:
                    return $"Unknown save result '{result}'.";
            }
        }

        private enum ChangeType
        {
            Add,
            Edit,
            Delete
        }

        private async Task<FeatureFlagsViewModel> GetModel()
        {
            var reference = await _storage.GetReferenceAsync();
            var lastUpdated = _cache.GetRefreshTimeOrNull();

            TimeSpan? timeSinceLastRefresh = null;
            if (lastUpdated.HasValue)
            {
                timeSinceLastRefresh = DateTimeOffset.UtcNow.Subtract(lastUpdated.Value);
            }

            return new FeatureFlagsViewModel
            {
                TimeSinceLastRefresh = timeSinceLastRefresh,
                RefreshInterval = _config.FeatureFlagsRefreshInterval,
                Features = GetFeaturesFromFlags(reference.Flags),
                Flights = GetFlightsFromFlags(reference.Flags),
                ContentId = reference.ContentId
            };
        }

        private List<FeatureFlagsFeatureViewModel> GetFeaturesFromFlags(FeatureFlags flags)
        {
            return flags.Features.Select(f => new FeatureFlagsFeatureViewModel(f.Key, f.Value)).ToList();
        }

        private List<FeatureFlagsFlightViewModel> GetFlightsFromFlags(FeatureFlags flags)
        {
            return flags.Flights.Select(f => new FeatureFlagsFlightViewModel(f.Key, f.Value)).ToList();
        }
    }
}

src/NuGetGallery/Areas/Admin/Views/Features/Index.cshtml
@model FeatureFlagsViewModel
@{
    ViewBag.Title = "Feature Flags";
}

<section role="main" class="container main-container page-revalidation">
    <h1>Feature flags</h1>

    @if (!Model.TimeSinceLastRefresh.HasValue)
    {
        @ViewHelpers.AlertWarning(
            @<text>
                The feature flags haven't loaded yet. Check the logs for errors.
            </text>)
    }
    else if (Model.IsOutdated)
    {
        @ViewHelpers.AlertWarning(
            @<text>
                The feature flags were last cached @Math.Round(Model.TimeSinceLastRefresh.Value.TotalSeconds) seconds ago
                but should refresh every @Model.RefreshInterval.TotalSeconds seconds. Check the logs for errors.
            </text>)
    }
    else
    {
        <p>
            The feature flags were last cached @Math.Round(Model.TimeSinceLastRefresh.Value.TotalSeconds) seconds ago
            and refresh every @Model.RefreshInterval.TotalSeconds seconds.
        </p>
    }

    <div class="form-group danger-zone">
        @ViewHelpers.Section(
            this,
            "features-expander",
            @<text>Features</text>,
            @<text><p>View and edit features.</p></text>,
            @<text>
                <table class="table">
                    <tr>
                        <th>Name</th>
                        <th>Current Status</th>
                        <th>Update Status</th>
                        <th>Delete</th>
                    </tr>
                    <tbody>
                        @foreach (var feature in Model.Features)
                        {
                            @Html.Partial("_EditFeature", new ModifyFeatureFlagsFeatureViewModel(feature, Model.ContentId))
                        }
                    </tbody>
                </table>

                @Html.Partial("_AddFeature", new ModifyFeatureFlagsFeatureViewModel { ContentId = Model.ContentId })
            </text>,
            expanded: true)
        
        @ViewHelpers.Section(
            this,
            "flights-expander",
            @<text>Flights</text>,
            @<text><p>View and edit flights.</p></text>,
            @<text>
                <table class="table">
                    <tr>
                        <th>Name</th>
                        <th>All</th>
                        <th>Site Admins</th>
                        <th>Accounts</th>
                        <th>Domains</th>
                        <th>Update</th>
                        <th>Delete</th>
                    </tr>
                    <tbody>
                        @foreach (var flight in Model.Flights)
                        {
                            @Html.Partial("_EditFlight", new ModifyFeatureFlagsFlightViewModel(flight, Model.ContentId))
                        }
                    </tbody>
                </table>

                @Html.Partial("_AddFlight", new ModifyFeatureFlagsFlightViewModel { ContentId = Model.ContentId })
            </text>,
            expanded: true)
    </div>
</section>

@section BottomScripts
{
    <script type="text/html" id="flight-array">
        <div class="form-group">
            <h5 data-bind="text: name"></h5>

            <!-- ko foreach: items -->
            <input type="hidden" data-bind="value: $data, attr: { name: $parent.name + '[]' }" />
            <!-- /ko -->

            <ul data-bind="foreach: items">
                <li>
                    <span data-bind="text: $data"></span>
                    <a class="icon-link" data-bind="click: $parent.remove.bind(this, $data)">
                        <i class="ms-Icon ms-Icon--Cancel" aria-hidden="true"></i>
                    </a>
                </li>
            </ul>

            <input type="text" data-bind="value: toAdd" />
            <input type="submit" class="btn btn-primary" data-bind="click: add" value="Add" />
        </div>
    </script>
    <script type="text/javascript">
        function FormDeleteConfirmation(event, name, typeName) {
            return confirm("Are you sure you would like to delete the " + typeName + " '" + name + "'?");
        }

        function FlightFormToggleAll(notAllId, submitId) {
            var $notAll = $('#' + notAllId);
            var isAll = $notAll.is(':visible');
            $notAll.toggle();
            
            var $input = $notAll.find('input');
            var $submit = $('#' + submitId);
            var offsetClass = 'col-sm-offset-7';
            if (isAll) {
                $input.attr('disabled', true);
                $submit.addClass(offsetClass);
            } else {
                $input.removeAttr('disabled');
                $submit.removeClass(offsetClass);
            }
        }

        function FlightArrayViewModel(name, initialItems) {
            var self = this;

            this.name = name;
            this.items = ko.observableArray(initialItems);

            this.toAdd = ko.observable();
            this.add = function () {
                if (self.toAdd()) {
                    self.items.push(self.toAdd());
                    self.toAdd('');
                }
            }

            this.remove = function (value) {
                self.items.remove(value);
            }
        }

        $(function () {
            $('.flight-array').each(function (index, object) {
                var $object = $(object);
                var name = $object.attr('name');
                var items = $object.attr('data-items').split(';');
                items = ko.utils.arrayFilter(items, function (item) {
                    return !!item
                });
                var model = new FlightArrayViewModel(name, items);
                ko.applyBindings(model, object);
            });
        });
    </script>
    @ViewHelpers.SectionsScript(this)
}

src/NuGetGallery/Areas/Admin/Views/Features/_AddFeature.cshtml
@using NuGetGallery
@model ModifyFeatureFlagsFeatureViewModel

<h3>
    Add
</h3>

@using (Html.BeginForm("AddFeature", "Features", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("ContentId", Model.ContentId)

    <div class="row">
        <div class="col-sm-6 form-group @Html.HasErrorFor(m => m.Name)">
            @Html.ShowLabelFor(m => m.Name)<br />
            @Html.ShowTextBoxFor(m => m.Name)
            @Html.ShowValidationMessagesFor(m => m.Name)
        </div>

        <div class="col-sm-3 form-group @Html.HasErrorFor(m => m.Status)">
            @Html.ShowLabelFor(m => m.Status)<br />
            @Html.EnumDropDownListFor(m => m.Status)
            @Html.ShowValidationMessagesFor(m => m.Status)
        </div>

        <div class="col-sm-3">
            <br />
            <input id="Add" type="submit" class="btn btn-primary form-control" value="Add" />
        </div>
    </div>
}

src/NuGetGallery/Areas/Admin/Views/Features/_AddFlight.cshtml
@using NuGetGallery
@model ModifyFeatureFlagsFlightViewModel
@{
    var formAddId = "flight-form-add";
    var formNotAllId = "flight-form-notall";
}

<h3>
    Add
</h3>

@using (Html.BeginForm("AddFlight", "Features", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("ContentId", Model.ContentId)

    <div class="row">
        <div class="col-sm-3 form-group @Html.HasErrorFor(m => m.Name)">
            @Html.ShowLabelFor(m => m.Name)<br />
            @Html.ShowTextBoxFor(m => m.Name)
            @Html.ShowValidationMessagesFor(m => m.Name)
        </div>

        <div class="col-sm-1 form-group @Html.HasErrorFor(m => m.All)" onchange="FlightFormToggleAll('@formNotAllId', '@formAddId')">
            @Html.ShowLabelFor(m => m.All)<br />
            @Html.ShowCheckboxFor(m => m.All)
            @Html.ShowValidationMessagesFor(m => m.All)
        </div>

        <div id="@formNotAllId" style="@(Model.All ? "display: none" : "")">
            <div class="col-sm-1 form-group @Html.HasErrorFor(m => m.SiteAdmins)">
                @Html.ShowLabelFor(m => m.SiteAdmins)<br />
                @Html.ShowCheckboxFor(m => m.SiteAdmins)
                @Html.ShowValidationMessagesFor(m => m.SiteAdmins)
            </div>

            <div class="flight-array col-sm-3" name="Accounts" data-items="@string.Join(";", Model.Accounts ?? new string[0])" data-bind="template: { name: 'flight-array', data: $data }"></div>
            <div class="flight-array col-sm-3" name="Domains" data-items="@string.Join(";", Model.Domains ?? new string[0])" data-bind="template: { name: 'flight-array', data: $data }"></div>
        </div>

        <div class="col-sm-1 @(Model.All ? "col-sm-offset-7" : "")" id="@formAddId">
            <br />
            <input id="Add" type="submit" class="btn btn-primary form-control" value="Add" />
        </div>
    </div>
}

src/NuGetGallery/Areas/Admin/Views/Features/_EditFeature.cshtml
@using NuGetGallery
@model ModifyFeatureFlagsFeatureViewModel

<tr>
    <td>@Model.Name</td>
    <td>@Model.Status.ToString()</td>
    <td>
        @using (Html.BeginForm("EditFeature", "Features", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden("ContentId", Model.ContentId)
            @Html.Hidden("Name", Model.Name)

            <div class="row">
                <div class="col-sm-6 form-group">
                    @Html.EnumDropDownListFor(m => m.Status)
                </div>
                <div class="col-sm-6 form-group">
                    <input id="Update" type="submit" class="btn btn-primary" value="Update" />
                </div>
            </div>
        }
    </td>
    <td>
        @using (Html.BeginForm("DeleteFeature", "Features", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden("ContentId", Model.ContentId)
            @Html.Hidden("Name", Model.Name)

            <input id="Delete" type="submit" class="btn btn-danger" value="Delete" onclick="return FormDeleteConfirmation(event, '@Model.Name', 'feature')" />
        }
    </td>
</tr>

src/NuGetGallery/Areas/Admin/Views/Features/_EditFlight.cshtml
@using NuGetGallery
@model ModifyFeatureFlagsFlightViewModel
@{ 
    var rowClass = "flight-" + Model.Name.Replace('.', '_');
    var rowFormId = rowClass + "-form";
    var rowFormSubmitId = rowClass + "-form-submit";
    var rowFormNotAllId = rowClass + "-form-notall";
}

<tr>
    <td>@Model.Name</td>
    <td class="@rowClass">@(Model.All ? "Enabled" : "Disabled")</td>
    <td class="@rowClass">@(Model.All ? "" : (Model.SiteAdmins ? "Enabled" : "Disabled"))</td>
    <td class="@rowClass">
        <ul>
            @foreach (var account in Model.Accounts)
            {
                <li>@account</li>
            }
        </ul>
    </td>
    <td class="@rowClass">
        <ul>
            @foreach (var domain in Model.Domains)
            {
                <li>@domain</li>
            }
        </ul>
    </td>
    <td class="@rowClass">
        <button class="btn btn-primary" onclick="$('.@rowClass').hide(); $('#@rowFormId').show()">Update</button>
    </td>
    <td colspan="5" id="@rowFormId" style="display: none">
        @using (Html.BeginForm("EditFlight", "Features", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden("ContentId", Model.ContentId)
            @Html.Hidden("Name", Model.Name)

            <div class="row">
                <div class="col-sm-2 form-group @Html.HasErrorFor(m => m.All)" onchange="FlightFormToggleAll('@rowFormNotAllId', '@rowFormSubmitId')">
                    @Html.ShowLabelFor(m => m.All)
                    @Html.ShowCheckboxFor(m => m.All)
                    @Html.ShowValidationMessagesFor(m => m.All)
                </div>

                <div id="@rowFormNotAllId" style="@(Model.All ? "display: none" : "")">
                    <div class="col-sm-2 form-group @Html.HasErrorFor(m => m.SiteAdmins)">
                        @Html.ShowLabelFor(m => m.SiteAdmins)
                        @Html.ShowCheckboxFor(m => m.SiteAdmins)
                        @Html.ShowValidationMessagesFor(m => m.SiteAdmins)
                    </div>

                    <div class="flight-array col-sm-3" name="Accounts" data-items="@string.Join(";", Model.Accounts ?? new string[0])" data-bind="template: { name: 'flight-array', data: $data }"></div>
                    <div class="flight-array col-sm-3" name="Domains" data-items="@string.Join(";", Model.Domains ?? new string[0])" data-bind="template: { name: 'flight-array', data: $data }"></div>
                </div>

                <div class="col-sm-2 @(Model.All ? "col-sm-offset-7" : "")" id="@rowFormSubmitId">
                    <div class="form-group">
                        <input id="Update" type="submit" class="btn btn-primary form-control" value="Update" />
                    </div>
                    <div class="form-group">
                        <button type="button" class="btn btn-default form-control" onclick="$('.@rowClass').show(); $('#@rowFormId').hide()">Cancel</button>
                    </div>
                </div>
            </div>
        }
    </td>
    <td>
        @using (Html.BeginForm("DeleteFlight", "Features", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden("ContentId", Model.ContentId)
            @Html.Hidden("Name", Model.Name)

            <div class="form-group">
                <input id="Delete" type="submit" class="btn btn-danger form-control" value="Delete" onclick="return FormDeleteConfirmation(event, '@Model.Name', 'flight')" />
            </div>
        }
    </td>
</tr>